## CHANGE this to the name of your plugin.
name: SlimySpirits

## CHANGE this to your username.
author: JustAHuman-xD

## CHANGE this to a meaninful but short description of your plugin.
description: Slimy Spirits is a Slimefun Addon that introduces Spirits and more to Slimefun4!

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.justahuman.slimyspirits.SlimySpirits

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/JustAHuman-xD/SlimySpirits

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.19

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun