name: SpiritsUnchained
author: JustAHuman-xD
description: Spirits Unchained is a Slimefun Addon that introduces Spirits and more to Slimefun4!

main: me.justahuman.spiritsunchained.SpiritsUnchained
website: https://github.com/JustAHuman-xD/SpiritsUnchained
version: ${project.version}

api-version: 1.19

depend:
- Slimefun